import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { PreviousRouteProvider } from "./_hooks/usePreviousRoute";
import { SocketProvider } from "./socket";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Script
        src="https://checkout.razorpay.com/v1/checkout.js"
        strategy="afterInteractive"
      />
      <body className={`  `} suppressHydrationWarning>
        <PreviousRouteProvider>
          <SocketProvider>
            <Toaster />
            {children}
          </SocketProvider>
        </PreviousRouteProvider>
      </body>
    </html>
  );
}
